APPNAME=signatumd
#VERSION=$(shell git describe --tags)
VERSION=1.1-armhf
NAMESPACE=squbs

build:  
	docker build -f Dockerfile.armhf -t $(NAMESPACE)/$(APPNAME) -t $(NAMESPACE)/$(APPNAME):$(VERSION) .
